# Licensed under the Apache-2.0 license
schema_version = "1"
repository = "chipsalliance/caliptra-sw"
hw_major_version = "1.0"
target_branch = "caliptra-1.x"
caliptra_variant = "core"
date = "2026-07-28T21:05:13.161281151+00:00"
commit_hash = "a02ebab0fda3d7e44c564062f77bea4cf32a0756"
job_id = "30107476345-build-bitstream"
segmented = false
name = "core-bitstream"
bin_url = "https://storage.googleapis.com/caliptra-github-ci-bitstreams/v1/a02ebab0fda3d7e44c564062f77bea4cf32a0756/caliptra_fpga.bin"
bin_hash = "d1fd7976d6fbbcf3c1fdb9614becee05c9ea0e718bd3a49d1d0481b3921a956b"
