# Licensed under the Apache-2.0 license
schema_version = "1"
repository = "chipsalliance/caliptra-sw"
hw_major_version = "1.x"
target_branch = "caliptra-1.x"
caliptra_variant = "core-latest-etrng"
date = "2026-08-05T22:53:32.416127319+00:00"
commit_hash = "a190c54bdf62456f6f99b261c03d1f4477209df1"
job_id = "31051400664-build-bitstream"
segmented = false
github_pr = 4049
name = "core-latest-etrng-bitstream"
bin_url = "https://storage.googleapis.com/caliptra-github-ci-bitstreams/v1/a190c54bdf62456f6f99b261c03d1f4477209df1/core-latest-etrng/caliptra_fpga.bin"
bin_hash = "3f65aeb0c4eeb86f7faff9fede5ab784b3758f4d18ddfc9658a0b20b93bdfac4"
