# Licensed under the Apache-2.0 license
schema_version = "1"
repository = "chipsalliance/caliptra-sw"
hw_major_version = "1.x"
target_branch = "caliptra-1.x"
caliptra_variant = "core-hw1.0-itrng"
date = "2026-08-05T22:59:06.273047625+00:00"
commit_hash = "a190c54bdf62456f6f99b261c03d1f4477209df1"
job_id = "31051400664-build-bitstream"
segmented = false
github_pr = 4049
name = "core-hw1.0-itrng-bitstream"
bin_url = "https://storage.googleapis.com/caliptra-github-ci-bitstreams/v1/a190c54bdf62456f6f99b261c03d1f4477209df1/core-hw1.0-itrng/caliptra_fpga.bin"
bin_hash = "4ebd0fa033579c99d249f23175a7c878b61640ce49ecfdcaf0745aaa8d1ffd7a"
