# Licensed under the Apache-2.0 license

[bitstream]
name = "subsystem-2.1"
url = "https://storage.googleapis.com/carl-caliptra-github-ci-bitstreams/scratch/runtime_2d3a0232.pdi"
hash = "b40e76a3b54328976bfe4c79cde422a94c044e2d9d90b267dc20872638c486db"
caliptra_variant = "subsystem"
caliptra_rtl_commit = "8885bd850d66a9f1ff45734da38f144a1c37b8df"
