# Licensed under the Apache-2.0 license

[package]
name = "caliptra-fmc-test-rom"
version = "0.1.0"
edition = "2021"

[features]
emu = ["caliptra-lib/emu"]
riscv = ["caliptra-rt/riscv"]

[[bin]]
name = "caliptra-fmc-test-rom"
required-features = ["riscv"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
caliptra-lib = { version = "0.1.0", path = "../../drivers" }
caliptra-registers = { version = "0.1.0", path = "../../registers" }
caliptra-rt = { path = "../../rt" }
cfg-if = "1.0.0"
ufmt = "0.2.0"

