# Licensed under the Apache-2.0 license.

[package]
name = "caliptra-image-types"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
arbitrary = { workspace = true, optional = true }
caliptra-cfi-derive.workspace = true
caliptra-cfi-lib.workspace = true
caliptra-error = { workspace = true, default-features = false }
caliptra-lms-types.workspace = true
memoffset.workspace = true
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
zerocopy.workspace = true
zeroize.workspace = true

[features]
default = ["std"]
std = ["dep:serde", "dep:serde_derive", "caliptra-lms-types/std"]
no-cfi = ["caliptra-lms-types/no-cfi"]
