# Licensed under the Apache-2.0 license.

[package]
name = "caliptra-image-types"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
zerocopy = "0.6.1"
memoffset = "0.8.0"

[features]
default = ["std"]
std = []