# Licensed under the Apache-2.0 license

[package]
name = "caliptra-image-openssl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
caliptra-drivers = {path = "../../drivers" }
caliptra-image-gen = { path = "../gen" }
caliptra-image-types = { path = "../types" }
openssl = "0.10.48"
anyhow = "1.0.70"