# Licensed under the Apache-2.0 license

[package]
name = "caliptra-hw-integration-test-runner-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
caliptra-api-types = {workspace = true, features = ["std"]}
caliptra_common.workspace = true
caliptra-error.workspace = true
caliptra-image-types.workspace = true
clap = {workspace = true, features = ["derive"]}
hex.workspace = true
serde.workspace = true
serde_derive.workspace = true
toml.workspace = true
x509-parser.workspace = true
