# Licensed under the Apache-2.0 license

[package]
name = "caliptra-runtime-test-bin"
version = "0.1.0"
edition = "2021"

[features]
runtime = ["caliptra-test-harness/runtime"]
riscv = [
    "caliptra-cpu/riscv",
    "caliptra-runtime/riscv",
    "caliptra-test-harness/riscv",
]
emu = [
    "caliptra-drivers/emu",
    "caliptra-runtime/emu",
    "caliptra-test-harness/emu",
]
fpga_realtime = ["caliptra-runtime/fpga_realtime"]
"hw-1.0" = ["caliptra-drivers/hw-1.0"]

[[bin]]
name = "boot"
path = "src/boot_tests.rs"
required-features = ["riscv"]

[[bin]]
name = "mbox"
path = "src/mbox_responder.rs"
required-features = ["riscv"]

[[bin]]
name = "persistent_rt"
path = "src/persistent_tests.rs"
required-features = ["riscv", "runtime"]

[[bin]]
name = "mock_rt_interact"
path = "src/mock_rt_test_interactive.rs"
required-features = ["riscv", "runtime"]


[build-dependencies]
caliptra_common = { workspace = true, default-features = false }
caliptra-gen-linker-scripts.workspace = true
cfg-if.workspace = true

[dependencies]
caliptra_common = { workspace = true, default-features = false }
caliptra-cpu.workspace = true
caliptra-drivers.workspace = true
caliptra-registers.workspace = true
caliptra-runtime = { workspace = true, default-features = false }
caliptra-test-harness.workspace = true
cfg-if.workspace = true
ufmt.workspace = true
zerocopy.workspace = true
