# Licensed under the Apache-2.0 license

[package]
name = "caliptra-runtime-test-bin"
version = "0.1.0"
edition = "2021"

[features]
runtime = ["caliptra-test-harness/runtime"]
riscv = [
    "caliptra-cpu/riscv",
    "caliptra-runtime/riscv",
    "caliptra-test-harness/riscv",
]
emu = [
    "caliptra-drivers/emu",
    "caliptra-runtime/emu",
    "caliptra-test-harness/emu",
]

[[bin]]
name = "boot"
path = "src/boot_tests.rs"
required-features = ["riscv"]

[[bin]]
name = "mbox"
path = "src/mbox_tests.rs"
required-features = ["riscv"]

[[bin]]
name = "cert"
path = "src/cert_tests.rs"
required-features = ["riscv"]

[[bin]]
name = "wdt"
path = "src/wdt_timeout_tests.rs"
required-features = ["riscv"]

[[bin]]
name = "keyvault"
path = "src/keyvault_tests.rs"
required-features = ["riscv"]

[[bin]]
name = "locked_dv"
path = "src/locked_dv_test.rs"
required-features = ["riscv"]

[build-dependencies]
caliptra_common = { workspace = true, default-features = false }
caliptra-gen-linker-scripts.workspace = true
cfg-if.workspace = true

[dependencies]
caliptra_common = { workspace = true, default-features = false }
caliptra-cpu.workspace = true
caliptra-drivers.workspace = true
caliptra-registers.workspace = true
caliptra-runtime = { workspace = true, default-features = false }
caliptra-test-harness.workspace = true
cfg-if.workspace = true
zerocopy.workspace = true
