# Licensed under the Apache-2.0 license

[package]
name = "caliptra-runtime-test-bin"
version = "0.1.0"
edition = "2021"

[features]
runtime = ["caliptra-test-harness/runtime"]
riscv = [
    "caliptra-cpu/riscv",
    "caliptra-runtime/riscv",
    "caliptra-test-harness/riscv",
]
emu = [
    "caliptra-drivers/emu",
    "caliptra-runtime/emu",
    "caliptra-test-harness/emu",
]

[[bin]]
name = "boot"
path = "src/boot_tests.rs"
required-features = ["riscv"]

[[bin]]
name = "mbox"
path = "src/mbox_tests.rs"
required-features = ["riscv"]

[[bin]]
name = "cert"
path = "src/cert_tests.rs"
required-features = ["riscv"]

[build-dependencies]
cfg-if = "1.0.0"
caliptra_common = { path = "../../common", default-features = false }
caliptra-gen-linker-scripts = { version = "0.1.0", path = "../../cpu/gen" }

[dependencies]
caliptra-test-harness = { path = "../../test-harness" }
caliptra-cpu = { version = "0.1.0", path = "../../cpu" }
caliptra-registers = { path = "../../registers" }
caliptra-runtime = { path = "..", default-features = false }
caliptra-drivers = { path = "../../drivers" }
caliptra_common = { path = "../../common", default-features = false }
cfg-if = "1.0.0"
zerocopy = "0.6.1"
