# Licensed under the Apache-2.0 license

[tasks.build]
command = "cargo"
install_crate = false
args = [
  "build",
  "--target",
  "riscv32imc-unknown-none-elf",
  "--features=riscv",
  "--profile=firmware", 
  "--bin=caliptra-fmc",
  "${@}",
]

[tasks.objcopy]
command = "cargo"
install_crate = false
args = [
  "objcopy",
  "--target",
  "riscv32imc-unknown-none-elf",
  "--features=riscv",
  "--profile=firmware", 
  "--bin=caliptra-fmc",
  "--",
  "-O",
  "binary",
  "/tmp/fmc.bin",
  "${@}",
]
dependencies = ["build"]

[tasks.objdump]
command = "cargo"
install_crate = false
args = [
  "objdump",
  "--target",
  "riscv32imc-unknown-none-elf",
  "--features=riscv",
  "--profile=firmware", 
  "--bin=fmc",
  "${@}",
  "--",
  "-d",
  "-z",
  "--no-print-imm-hex",
  "--disassembler-options=no-aliases",  
]
dependencies = ["build"]

[tasks.emu]
command = "cargo"
install_crate = false
args = [
  "run",
  "--manifest-path",
  "../sw-emulator/Cargo.toml",
  "--bin",
  "caliptra-emu",
  "--",
  "--rom",
  "/tmp/test-rom.bin",
  "--firmware",
  "/tmp/fmc.bin"
]
dependencies = ["objcopy"]

[tasks.test-rom]
script = "(cd test-rom && cargo make objcopy)"
dependencies = ["objcopy"]

[tasks.workflow]
dependencies = [
  "test-rom",
  "emu"
]