# Licensed under the Apache-2.0 license

[workspace]

members = [
  "app",
  "compliance-test",
  "lib/cpu",
  "lib/crypto",
  "lib/derive",
  "lib/periph",
  "lib/types",
]

exclude = [
  "example",
]
