// Licensed under the Apache-2.0 license.
//
// generated by caliptra_registers_generator with caliptra-rtl repo at 544ee8bd350c5d09c7a0c8e01134274b7ed48b3a
//
#![allow(clippy::doc_lazy_continuation)]
#![allow(clippy::erasing_op)]
#![allow(clippy::identity_op)]
/// A zero-sized type that represents ownership of this
/// peripheral, used to get access to a Register lock. Most
/// programs create one of these in unsafe code near the top of
/// main(), and pass it to the driver responsible for managing
/// all access to the hardware.
pub struct Sha3 {
    _priv: (),
}
impl Sha3 {
    pub const PTR: *mut u32 = 0x10041000 as *mut u32;
    /// # Safety
    ///
    /// Caller must ensure that all concurrent use of this
    /// peripheral in the firmware is done so in a compatible
    /// way. The simplest way to enforce this is to only call
    /// this function once.
    #[inline(always)]
    pub unsafe fn new() -> Self {
        Self { _priv: () }
    }
    /// Returns a register block that can be used to read
    /// registers from this peripheral, but cannot write.
    #[inline(always)]
    pub fn regs(&self) -> RegisterBlock<ureg::RealMmio> {
        RegisterBlock {
            ptr: Self::PTR,
            mmio: core::default::Default::default(),
        }
    }
    /// Return a register block that can be used to read and
    /// write this peripheral's registers.
    #[inline(always)]
    pub fn regs_mut(&mut self) -> RegisterBlock<ureg::RealMmioMut> {
        RegisterBlock {
            ptr: Self::PTR,
            mmio: core::default::Default::default(),
        }
    }
}
#[allow(dead_code)]
#[derive(Clone, Copy)]
pub struct RegisterBlock<TMmio: ureg::Mmio + core::borrow::Borrow<TMmio>> {
    ptr: *mut u32,
    mmio: TMmio,
}
impl<TMmio: ureg::Mmio + core::default::Default> RegisterBlock<TMmio> {
    /// # Safety
    ///
    /// The caller is responsible for ensuring that ptr is valid for
    /// volatile reads and writes at any of the offsets in this register
    /// block.
    #[inline(always)]
    pub unsafe fn new(ptr: *mut u32) -> Self {
        Self {
            ptr,
            mmio: core::default::Default::default(),
        }
    }
}
impl<TMmio: ureg::Mmio> RegisterBlock<TMmio> {
    /// # Safety
    ///
    /// The caller is responsible for ensuring that ptr is valid for
    /// volatile reads and writes at any of the offsets in this register
    /// block.
    #[inline(always)]
    pub unsafe fn new_with_mmio(ptr: *mut u32, mmio: TMmio) -> Self {
        Self { ptr, mmio }
    }
    /// Two 32-bit read-only registers representing the name
    /// of SHA3/SHAKE component.
    ///
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn name(&self) -> ureg::Array<2, ureg::RegRef<crate::sha3::meta::Name, &TMmio>> {
        unsafe {
            ureg::Array::new_with_mmio(
                self.ptr.wrapping_add(0 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Two 32-bit read-only registers representing the version
    /// of SHA3/SHAKE component.
    ///
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn version(&self) -> ureg::Array<2, ureg::RegRef<crate::sha3::meta::Version, &TMmio>> {
        unsafe {
            ureg::Array::new_with_mmio(
                self.ptr.wrapping_add(8 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`sha3::regs::AlertTestReadVal`]; Write value: [`sha3::regs::AlertTestWriteVal`]
    #[inline(always)]
    pub fn alert_test(&self) -> ureg::RegRef<crate::sha3::meta::AlertTest, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x1c / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`sha3::regs::CfgRegwenReadVal`]; Write value: [`sha3::regs::CfgRegwenWriteVal`]
    #[inline(always)]
    pub fn cfg_regwen(&self) -> ureg::RegRef<crate::sha3::meta::CfgRegwen, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x20 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// This register is shadowed and protected by CFG_REGWEN.en
    /// 1. Two subsequent write operation are required to change its content,
    /// If the two write operations try to set a different value, a recoverable alert is triggered (See Status Register).
    /// 2. A read operation clears the internal phase tracking.
    /// 3. If storage error(~staged_reg!=committed_reg) happen, it will trigger fatal fault alert
    ///
    /// Read value: [`sha3::regs::CfgShadowedReadVal`]; Write value: [`sha3::regs::CfgShadowedWriteVal`]
    #[inline(always)]
    pub fn cfg_shadowed(&self) -> ureg::RegRef<crate::sha3::meta::CfgShadowed, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x24 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`sha3::regs::CmdReadVal`]; Write value: [`sha3::regs::CmdWriteVal`]
    #[inline(always)]
    pub fn cmd(&self) -> ureg::RegRef<crate::sha3::meta::Cmd, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x28 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Read value: [`sha3::regs::StatusReadVal`]; Write value: [`sha3::regs::StatusWriteVal`]
    #[inline(always)]
    pub fn status(&self) -> ureg::RegRef<crate::sha3::meta::Status, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x2c / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// SHA3 Error Code
    ///
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn err_code(&self) -> ureg::RegRef<crate::sha3::meta::ErrCode, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0xd0 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Keccak State (1600 bit) memory.
    /// The software can get the processed digest by reading this memory
    /// region. Unlike MSG_FIFO, STATE memory space sees the addr[9:0].
    /// If Masking feature is enabled, the software reads two shares from
    /// this memory space.
    /// 0x200 - 0x2C7: State share
    /// for Keccak State access:
    /// 1. Output length <= rate length, sha3_done will be raised or software can poll STATUS.squeeze become 1.
    /// 2. Output length > rate length, after software read 1st keccak state, software should issue run cmd to trigger keccak round logic to run full 24 rounds.
    /// And then software should check STATUS.squeeze register field for the readiness of STATE value(SHA3 FSM become MANUAL_RUN before keccak state complete).
    ///
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn state(&self) -> ureg::Array<64, ureg::RegRef<crate::sha3::meta::State, &TMmio>> {
        unsafe {
            ureg::Array::new_with_mmio(
                self.ptr.wrapping_add(0x200 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Message FIFO. window size is 2048 bytes.
    /// Any write operation to this window will be appended to MSG_FIFO. SW can
    /// simply write bytes/words to any address within this address range.
    /// Ordering and packing of the incoming bytes/words are handled
    /// internally. Therefore, the least significant 10 bits of the address
    /// are ignored.
    ///
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn msg_fifo(&self) -> ureg::Array<64, ureg::RegRef<crate::sha3::meta::MsgFifo, &TMmio>> {
        unsafe {
            ureg::Array::new_with_mmio(
                self.ptr.wrapping_add(0xc00 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    #[inline(always)]
    pub fn intr_block_rf(&self) -> IntrBlockRfBlock<&TMmio> {
        IntrBlockRfBlock {
            ptr: unsafe { self.ptr.add(0x400 / core::mem::size_of::<u32>()) },
            mmio: core::borrow::Borrow::borrow(&self.mmio),
        }
    }
}
#[derive(Clone, Copy)]
pub struct IntrBlockRfBlock<TMmio: ureg::Mmio + core::borrow::Borrow<TMmio>> {
    ptr: *mut u32,
    mmio: TMmio,
}
impl<TMmio: ureg::Mmio> IntrBlockRfBlock<TMmio> {
    /// Dedicated register with one bit for each event type that may produce an interrupt.
    ///
    /// Read value: [`sha512_acc::regs::GlobalIntrEnTReadVal`]; Write value: [`sha512_acc::regs::GlobalIntrEnTWriteVal`]
    #[inline(always)]
    pub fn global_intr_en_r(
        &self,
    ) -> ureg::RegRef<crate::sha3::meta::IntrBlockRfGlobalIntrEnR, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Dedicated register with one bit for each event that may produce an interrupt.
    ///
    /// Read value: [`sha3::regs::ErrorIntrEnTReadVal`]; Write value: [`sha3::regs::ErrorIntrEnTWriteVal`]
    #[inline(always)]
    pub fn error_intr_en_r(
        &self,
    ) -> ureg::RegRef<crate::sha3::meta::IntrBlockRfErrorIntrEnR, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(4 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Dedicated register with one bit for each event that may produce an interrupt.
    ///
    /// Read value: [`sha3::regs::NotifIntrEnTReadVal`]; Write value: [`sha3::regs::NotifIntrEnTWriteVal`]
    #[inline(always)]
    pub fn notif_intr_en_r(
        &self,
    ) -> ureg::RegRef<crate::sha3::meta::IntrBlockRfNotifIntrEnR, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(8 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Single bit indicating occurrence of any interrupt event
    /// of a given type. E.g. Notifications and Errors may drive
    /// to two separate interrupt registers. There may be
    /// multiple sources of Notifications or Errors that are
    /// aggregated into a single interrupt pin for that
    /// respective type. That pin feeds through this register
    /// in order to apply a global enablement of that interrupt
    /// event type.
    /// Nonsticky assertion.
    ///
    /// Read value: [`sha512_acc::regs::GlobalIntrTReadVal`]; Write value: [`sha512_acc::regs::GlobalIntrTWriteVal`]
    #[inline(always)]
    pub fn error_global_intr_r(
        &self,
    ) -> ureg::RegRef<crate::sha3::meta::IntrBlockRfErrorGlobalIntrR, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0xc / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Single bit indicating occurrence of any interrupt event
    /// of a given type. E.g. Notifications and Errors may drive
    /// to two separate interrupt registers. There may be
    /// multiple sources of Notifications or Errors that are
    /// aggregated into a single interrupt pin for that
    /// respective type. That pin feeds through this register
    /// in order to apply a global enablement of that interrupt
    /// event type.
    /// Nonsticky assertion.
    ///
    /// Read value: [`sha512_acc::regs::GlobalIntrTReadVal`]; Write value: [`sha512_acc::regs::GlobalIntrTWriteVal`]
    #[inline(always)]
    pub fn notif_global_intr_r(
        &self,
    ) -> ureg::RegRef<crate::sha3::meta::IntrBlockRfNotifGlobalIntrR, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x10 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Single bit indicating occurrence of each interrupt event.
    /// Sticky, level assertion, write-1-to-clear.
    /// SHA3 error occurred. ERR_CODE register shows the details
    ///
    /// Read value: [`sha3::regs::ErrorIntrTReadVal`]; Write value: [`sha3::regs::ErrorIntrTWriteVal`]
    #[inline(always)]
    pub fn error_internal_intr_r(
        &self,
    ) -> ureg::RegRef<crate::sha3::meta::IntrBlockRfErrorInternalIntrR, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x14 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Single bit indicating occurrence of each interrupt event.
    /// Sticky, level assertion, write-1-to-clear.
    ///
    /// Read value: [`sha3::regs::NotifIntrTReadVal`]; Write value: [`sha3::regs::NotifIntrTWriteVal`]
    #[inline(always)]
    pub fn notif_internal_intr_r(
        &self,
    ) -> ureg::RegRef<crate::sha3::meta::IntrBlockRfNotifInternalIntrR, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x18 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Single bit for each interrupt event allows SW to manually
    /// trigger occurrence of that event. Upon SW write, the trigger bit
    /// will pulse for 1 cycle then clear to 0. The pulse on the
    /// trigger register bit results in the corresponding interrupt
    /// status bit being set to 1.
    ///
    /// Read value: [`sha3::regs::ErrorIntrTrigTReadVal`]; Write value: [`sha3::regs::ErrorIntrTrigTWriteVal`]
    #[inline(always)]
    pub fn error_intr_trig_r(
        &self,
    ) -> ureg::RegRef<crate::sha3::meta::IntrBlockRfErrorIntrTrigR, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x1c / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Single bit for each interrupt event allows SW to manually
    /// trigger occurrence of that event. Upon SW write, the trigger bit
    /// will pulse for 1 cycle then clear to 0. The pulse on the
    /// trigger register bit results in the corresponding interrupt
    /// status bit being set to 1.
    ///
    /// Read value: [`sha3::regs::NotifIntrTrigTReadVal`]; Write value: [`sha3::regs::NotifIntrTrigTWriteVal`]
    #[inline(always)]
    pub fn notif_intr_trig_r(
        &self,
    ) -> ureg::RegRef<crate::sha3::meta::IntrBlockRfNotifIntrTrigR, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x20 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Provides statistics about the number of events that have
    /// occurred.
    /// Will not overflow ('incrsaturate').
    ///
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn sha3_error_intr_count_r(
        &self,
    ) -> ureg::RegRef<crate::sha3::meta::IntrBlockRfSha3ErrorIntrCountR, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x100 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Provides statistics about the number of events that have
    /// occurred.
    /// Will not overflow ('incrsaturate').
    ///
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn error1_intr_count_r(
        &self,
    ) -> ureg::RegRef<crate::sha3::meta::IntrBlockRfError1IntrCountR, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x104 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Provides statistics about the number of events that have
    /// occurred.
    /// Will not overflow ('incrsaturate').
    ///
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn error2_intr_count_r(
        &self,
    ) -> ureg::RegRef<crate::sha3::meta::IntrBlockRfError2IntrCountR, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x108 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Provides statistics about the number of events that have
    /// occurred.
    /// Will not overflow ('incrsaturate').
    ///
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn error3_intr_count_r(
        &self,
    ) -> ureg::RegRef<crate::sha3::meta::IntrBlockRfError3IntrCountR, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x10c / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Provides statistics about the number of events that have
    /// occurred.
    /// Will not overflow ('incrsaturate').
    ///
    /// Read value: [`u32`]; Write value: [`u32`]
    #[inline(always)]
    pub fn notif_cmd_done_intr_count_r(
        &self,
    ) -> ureg::RegRef<crate::sha3::meta::IntrBlockRfNotifCmdDoneIntrCountR, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x180 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Trigger the event counter to increment based on observing
    /// the rising edge of an interrupt event input from the
    /// Hardware. The same input signal that causes an interrupt
    /// event to be set (sticky) also causes this signal to pulse
    /// for 1 clock cycle, resulting in the event counter
    /// incrementing by 1 for every interrupt event.
    /// This is implemented as a down-counter (1-bit) that will
    /// decrement immediately on being set - resulting in a pulse
    ///
    /// Read value: [`sha512_acc::regs::IntrCountIncrTReadVal`]; Write value: [`sha512_acc::regs::IntrCountIncrTWriteVal`]
    #[inline(always)]
    pub fn sha3_error_intr_count_incr_r(
        &self,
    ) -> ureg::RegRef<crate::sha3::meta::IntrBlockRfSha3ErrorIntrCountIncrR, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x200 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Trigger the event counter to increment based on observing
    /// the rising edge of an interrupt event input from the
    /// Hardware. The same input signal that causes an interrupt
    /// event to be set (sticky) also causes this signal to pulse
    /// for 1 clock cycle, resulting in the event counter
    /// incrementing by 1 for every interrupt event.
    /// This is implemented as a down-counter (1-bit) that will
    /// decrement immediately on being set - resulting in a pulse
    ///
    /// Read value: [`sha512_acc::regs::IntrCountIncrTReadVal`]; Write value: [`sha512_acc::regs::IntrCountIncrTWriteVal`]
    #[inline(always)]
    pub fn error1_intr_count_incr_r(
        &self,
    ) -> ureg::RegRef<crate::sha3::meta::IntrBlockRfError1IntrCountIncrR, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x204 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Trigger the event counter to increment based on observing
    /// the rising edge of an interrupt event input from the
    /// Hardware. The same input signal that causes an interrupt
    /// event to be set (sticky) also causes this signal to pulse
    /// for 1 clock cycle, resulting in the event counter
    /// incrementing by 1 for every interrupt event.
    /// This is implemented as a down-counter (1-bit) that will
    /// decrement immediately on being set - resulting in a pulse
    ///
    /// Read value: [`sha512_acc::regs::IntrCountIncrTReadVal`]; Write value: [`sha512_acc::regs::IntrCountIncrTWriteVal`]
    #[inline(always)]
    pub fn error2_intr_count_incr_r(
        &self,
    ) -> ureg::RegRef<crate::sha3::meta::IntrBlockRfError2IntrCountIncrR, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x208 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Trigger the event counter to increment based on observing
    /// the rising edge of an interrupt event input from the
    /// Hardware. The same input signal that causes an interrupt
    /// event to be set (sticky) also causes this signal to pulse
    /// for 1 clock cycle, resulting in the event counter
    /// incrementing by 1 for every interrupt event.
    /// This is implemented as a down-counter (1-bit) that will
    /// decrement immediately on being set - resulting in a pulse
    ///
    /// Read value: [`sha512_acc::regs::IntrCountIncrTReadVal`]; Write value: [`sha512_acc::regs::IntrCountIncrTWriteVal`]
    #[inline(always)]
    pub fn error3_intr_count_incr_r(
        &self,
    ) -> ureg::RegRef<crate::sha3::meta::IntrBlockRfError3IntrCountIncrR, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x20c / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
    /// Trigger the event counter to increment based on observing
    /// the rising edge of an interrupt event input from the
    /// Hardware. The same input signal that causes an interrupt
    /// event to be set (sticky) also causes this signal to pulse
    /// for 1 clock cycle, resulting in the event counter
    /// incrementing by 1 for every interrupt event.
    /// This is implemented as a down-counter (1-bit) that will
    /// decrement immediately on being set - resulting in a pulse
    ///
    /// Read value: [`sha512_acc::regs::IntrCountIncrTReadVal`]; Write value: [`sha512_acc::regs::IntrCountIncrTWriteVal`]
    #[inline(always)]
    pub fn notif_cmd_done_intr_count_incr_r(
        &self,
    ) -> ureg::RegRef<crate::sha3::meta::IntrBlockRfNotifCmdDoneIntrCountIncrR, &TMmio> {
        unsafe {
            ureg::RegRef::new_with_mmio(
                self.ptr.wrapping_add(0x210 / core::mem::size_of::<u32>()),
                core::borrow::Borrow::borrow(&self.mmio),
            )
        }
    }
}
/// A zero-sized type that represents ownership of this
/// peripheral, used to get access to a Register lock. Most
/// programs create one of these in unsafe code near the top of
/// main(), and pass it to the driver responsible for managing
/// all access to the hardware.
pub struct IntrBlockRf {
    _priv: (),
}
impl IntrBlockRf {
    pub const PTR: *mut u32 = 0x400 as *mut u32;
    /// # Safety
    ///
    /// Caller must ensure that all concurrent use of this
    /// peripheral in the firmware is done so in a compatible
    /// way. The simplest way to enforce this is to only call
    /// this function once.
    #[inline(always)]
    pub unsafe fn new() -> Self {
        Self { _priv: () }
    }
    /// Returns a register block that can be used to read
    /// registers from this peripheral, but cannot write.
    #[inline(always)]
    pub fn regs(&self) -> RegisterBlock<ureg::RealMmio> {
        RegisterBlock {
            ptr: Self::PTR,
            mmio: core::default::Default::default(),
        }
    }
    /// Return a register block that can be used to read and
    /// write this peripheral's registers.
    #[inline(always)]
    pub fn regs_mut(&mut self) -> RegisterBlock<ureg::RealMmioMut> {
        RegisterBlock {
            ptr: Self::PTR,
            mmio: core::default::Default::default(),
        }
    }
}
pub mod regs {
    //! Types that represent the values held by registers.
    #[derive(Clone, Copy)]
    pub struct AlertTestWriteVal(u32);
    impl AlertTestWriteVal {
        /// Write 1 to trigger one alert event of this kind.
        #[inline(always)]
        pub fn recov_operation_err(self, val: bool) -> Self {
            Self((self.0 & !(1 << 0)) | (u32::from(val) << 0))
        }
        /// Write 1 to trigger one alert event of this kind.
        #[inline(always)]
        pub fn fatal_fault_err(self, val: bool) -> Self {
            Self((self.0 & !(1 << 1)) | (u32::from(val) << 1))
        }
    }
    impl From<u32> for AlertTestWriteVal {
        #[inline(always)]
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<AlertTestWriteVal> for u32 {
        #[inline(always)]
        fn from(val: AlertTestWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct CfgRegwenReadVal(u32);
    impl CfgRegwenReadVal {
        /// Configuration enable.
        #[inline(always)]
        pub fn en(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
    }
    impl From<u32> for CfgRegwenReadVal {
        #[inline(always)]
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<CfgRegwenReadVal> for u32 {
        #[inline(always)]
        fn from(val: CfgRegwenReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct CfgShadowedReadVal(u32);
    impl CfgShadowedReadVal {
        /// Hashing Strength, Protected by CFG_REGWEN.en
        /// bit field to select the security strength of SHA3 hashing engine.
        /// If mode field is set to SHAKE, only 128 and 256 strength can be selected.
        /// Other value will result error when hashing starts.
        #[inline(always)]
        pub fn kstrength(&self) -> u32 {
            (self.0 >> 1) & 7
        }
        /// Keccak hashing mode, Protected by CFG_REGWEN.en
        /// This module supports SHA3 main hashing algorithm and the part of its derived functions,
        /// SHAKE with limitations. This field is to select the mode.
        #[inline(always)]
        pub fn mode(&self) -> u32 {
            (self.0 >> 4) & 3
        }
        /// Protected by CFG_REGWEN.en
        /// If 1 then each individual multi-byte value, regardless of its alignment,
        /// written to MSG_FIFO will be added to the message in big-endian byte order.
        /// If 0, each value will be added to the message in little-endian byte order.
        /// A message written to MSG_FIFO one byte at a time will not be affected by this setting.
        /// From a hardware perspective byte swaps are performed on a TL-UL word granularity.
        #[inline(always)]
        pub fn msg_endianness(&self) -> bool {
            ((self.0 >> 8) & 1) != 0
        }
        /// Protected by CFG_REGWEN.en
        /// If 1 then each individual multi-byte value, regardless of its alignment,
        /// written to MSG_FIFO will be added to the message in big-endian byte order.
        /// If 0, each value will be added to the message in little-endian byte order.
        /// A message written to MSG_FIFO one byte at a time will not be affected by this setting.
        /// From a hardware perspective byte swaps are performed on a TL-UL word granularity.
        #[inline(always)]
        pub fn state_endianness(&self) -> bool {
            ((self.0 >> 9) & 1) != 0
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        #[inline(always)]
        pub fn modify(self) -> CfgShadowedWriteVal {
            CfgShadowedWriteVal(self.0)
        }
    }
    impl From<u32> for CfgShadowedReadVal {
        #[inline(always)]
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<CfgShadowedReadVal> for u32 {
        #[inline(always)]
        fn from(val: CfgShadowedReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct CfgShadowedWriteVal(u32);
    impl CfgShadowedWriteVal {
        /// Hashing Strength, Protected by CFG_REGWEN.en
        /// bit field to select the security strength of SHA3 hashing engine.
        /// If mode field is set to SHAKE, only 128 and 256 strength can be selected.
        /// Other value will result error when hashing starts.
        #[inline(always)]
        pub fn kstrength(self, val: u32) -> Self {
            Self((self.0 & !(7 << 1)) | ((val & 7) << 1))
        }
        /// Keccak hashing mode, Protected by CFG_REGWEN.en
        /// This module supports SHA3 main hashing algorithm and the part of its derived functions,
        /// SHAKE with limitations. This field is to select the mode.
        #[inline(always)]
        pub fn mode(self, val: u32) -> Self {
            Self((self.0 & !(3 << 4)) | ((val & 3) << 4))
        }
        /// Protected by CFG_REGWEN.en
        /// If 1 then each individual multi-byte value, regardless of its alignment,
        /// written to MSG_FIFO will be added to the message in big-endian byte order.
        /// If 0, each value will be added to the message in little-endian byte order.
        /// A message written to MSG_FIFO one byte at a time will not be affected by this setting.
        /// From a hardware perspective byte swaps are performed on a TL-UL word granularity.
        #[inline(always)]
        pub fn msg_endianness(self, val: bool) -> Self {
            Self((self.0 & !(1 << 8)) | (u32::from(val) << 8))
        }
        /// Protected by CFG_REGWEN.en
        /// If 1 then each individual multi-byte value, regardless of its alignment,
        /// written to MSG_FIFO will be added to the message in big-endian byte order.
        /// If 0, each value will be added to the message in little-endian byte order.
        /// A message written to MSG_FIFO one byte at a time will not be affected by this setting.
        /// From a hardware perspective byte swaps are performed on a TL-UL word granularity.
        #[inline(always)]
        pub fn state_endianness(self, val: bool) -> Self {
            Self((self.0 & !(1 << 9)) | (u32::from(val) << 9))
        }
    }
    impl From<u32> for CfgShadowedWriteVal {
        #[inline(always)]
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<CfgShadowedWriteVal> for u32 {
        #[inline(always)]
        fn from(val: CfgShadowedWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct CmdReadVal(u32);
    impl CmdReadVal {
        /// Issues a command to the SHA3 IP. The command is sparse encoded.
        /// To prevent sw from writing multiple commands at once, the field is defined as enum.
        /// Always return 0 for SW reads.
        /// START: Writing 6'b011101 or dec 29 into this field when SHA3/SHAKE is in idle, SHA3/SHAKE begins its operation and start absorbing.
        /// PROCESS: Writing 6'b101110 or dec 46 into this field when SHA3/SHAKE began its operation and received the entire message, it computes the digest or signing.
        /// RUN: The run field is used in the sponge squeezing stage.
        /// It triggers the keccak round logic to run full 24 rounds.
        /// This is optional and used when software needs more digest bits than the keccak rate.
        /// It only affects when the SHA3/SHAKE operation is completed.
        /// DONE: Writing 6'b010110 or dec 22 into this field when SHA3 squeezing is completed,
        /// SHA3/SHAKE hashing engine clears internal variables and goes back to Idle state for next command.
        #[inline(always)]
        pub fn cmd(&self) -> u32 {
            (self.0 >> 0) & 0x3f
        }
        /// When error occurs and one of the state machine stays at Error handling state,
        /// SW may process the error based on ERR_CODE, then let FSM back to the reset state.
        /// Always return 0 for SW reads.
        #[inline(always)]
        pub fn err_processed(&self) -> bool {
            ((self.0 >> 10) & 1) != 0
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        #[inline(always)]
        pub fn modify(self) -> CmdWriteVal {
            CmdWriteVal(self.0)
        }
    }
    impl From<u32> for CmdReadVal {
        #[inline(always)]
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<CmdReadVal> for u32 {
        #[inline(always)]
        fn from(val: CmdReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct CmdWriteVal(u32);
    impl CmdWriteVal {
        /// Issues a command to the SHA3 IP. The command is sparse encoded.
        /// To prevent sw from writing multiple commands at once, the field is defined as enum.
        /// Always return 0 for SW reads.
        /// START: Writing 6'b011101 or dec 29 into this field when SHA3/SHAKE is in idle, SHA3/SHAKE begins its operation and start absorbing.
        /// PROCESS: Writing 6'b101110 or dec 46 into this field when SHA3/SHAKE began its operation and received the entire message, it computes the digest or signing.
        /// RUN: The run field is used in the sponge squeezing stage.
        /// It triggers the keccak round logic to run full 24 rounds.
        /// This is optional and used when software needs more digest bits than the keccak rate.
        /// It only affects when the SHA3/SHAKE operation is completed.
        /// DONE: Writing 6'b010110 or dec 22 into this field when SHA3 squeezing is completed,
        /// SHA3/SHAKE hashing engine clears internal variables and goes back to Idle state for next command.
        #[inline(always)]
        pub fn cmd(self, val: u32) -> Self {
            Self((self.0 & !(0x3f << 0)) | ((val & 0x3f) << 0))
        }
        /// When error occurs and one of the state machine stays at Error handling state,
        /// SW may process the error based on ERR_CODE, then let FSM back to the reset state.
        /// Always return 0 for SW reads.
        #[inline(always)]
        pub fn err_processed(self, val: bool) -> Self {
            Self((self.0 & !(1 << 10)) | (u32::from(val) << 10))
        }
    }
    impl From<u32> for CmdWriteVal {
        #[inline(always)]
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<CmdWriteVal> for u32 {
        #[inline(always)]
        fn from(val: CmdWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct StatusReadVal(u32);
    impl StatusReadVal {
        /// If 1, SHA3 hashing engine is in idle state.
        #[inline(always)]
        pub fn sha3_idle(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
        /// If 1, SHA3 is receiving message stream and processing it
        #[inline(always)]
        pub fn sha3_absorb(&self) -> bool {
            ((self.0 >> 1) & 1) != 0
        }
        /// If 1, SHA3 completes sponge absorbing stage. In this stage, SW can manually run the hashing engine.
        #[inline(always)]
        pub fn sha3_squeeze(&self) -> bool {
            ((self.0 >> 2) & 1) != 0
        }
        /// Count of occupied entries in the message FIFO.
        #[inline(always)]
        pub fn fifo_depth(&self) -> u32 {
            (self.0 >> 8) & 0x1f
        }
        /// Message FIFO Empty indicator.
        /// The FIFO's Pass parameter is set to 1'b 1. So, by default, if the SHA engine is ready, the write data to FIFO just passes through.
        /// In this case, fifo_depth remains 0. fifo_empty, however, lowers the value to 0 for a cycle, then goes back to the empty state, 1.
        /// See the Message FIFO section in the spec for the reason.
        #[inline(always)]
        pub fn fifo_empty(&self) -> bool {
            ((self.0 >> 14) & 1) != 0
        }
        /// Message FIFO Full indicator.
        #[inline(always)]
        pub fn fifo_full(&self) -> bool {
            ((self.0 >> 15) & 1) != 0
        }
        /// No fatal fault has occurred inside the SHA3 unit (0).
        /// A fatal fault has occured and the SHA3 unit needs to be reset (1),
        /// Examples for such faults include i) TL-UL bus integrity fault
        /// ii) storage errors in the shadow registers
        /// iii) errors in the message, round, or key counter
        /// iv) any internal FSM entering an invalid state.
        #[inline(always)]
        pub fn alert_fatal_fault(&self) -> bool {
            ((self.0 >> 16) & 1) != 0
        }
        /// An update error has not occurred (0) or has occured (1) in the shadowed Control Register.
        /// SHA3 operation needs to be restarted by re-writing the Control Register.
        #[inline(always)]
        pub fn alert_recov_ctrl_update_err(&self) -> bool {
            ((self.0 >> 17) & 1) != 0
        }
    }
    impl From<u32> for StatusReadVal {
        #[inline(always)]
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<StatusReadVal> for u32 {
        #[inline(always)]
        fn from(val: StatusReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ErrorIntrEnTReadVal(u32);
    impl ErrorIntrEnTReadVal {
        /// Enable bit for Event 0.
        /// If enabled, interrupt will be asserted
        /// if there is a SHAKE configuration error.
        #[inline(always)]
        pub fn sha3_error_en(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
        /// Enable bit for Event 1
        #[inline(always)]
        pub fn error1_en(&self) -> bool {
            ((self.0 >> 1) & 1) != 0
        }
        /// Enable bit for Event 2
        #[inline(always)]
        pub fn error2_en(&self) -> bool {
            ((self.0 >> 2) & 1) != 0
        }
        /// Enable bit for Event 3
        #[inline(always)]
        pub fn error3_en(&self) -> bool {
            ((self.0 >> 3) & 1) != 0
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        #[inline(always)]
        pub fn modify(self) -> ErrorIntrEnTWriteVal {
            ErrorIntrEnTWriteVal(self.0)
        }
    }
    impl From<u32> for ErrorIntrEnTReadVal {
        #[inline(always)]
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ErrorIntrEnTReadVal> for u32 {
        #[inline(always)]
        fn from(val: ErrorIntrEnTReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ErrorIntrEnTWriteVal(u32);
    impl ErrorIntrEnTWriteVal {
        /// Enable bit for Event 0.
        /// If enabled, interrupt will be asserted
        /// if there is a SHAKE configuration error.
        #[inline(always)]
        pub fn sha3_error_en(self, val: bool) -> Self {
            Self((self.0 & !(1 << 0)) | (u32::from(val) << 0))
        }
        /// Enable bit for Event 1
        #[inline(always)]
        pub fn error1_en(self, val: bool) -> Self {
            Self((self.0 & !(1 << 1)) | (u32::from(val) << 1))
        }
        /// Enable bit for Event 2
        #[inline(always)]
        pub fn error2_en(self, val: bool) -> Self {
            Self((self.0 & !(1 << 2)) | (u32::from(val) << 2))
        }
        /// Enable bit for Event 3
        #[inline(always)]
        pub fn error3_en(self, val: bool) -> Self {
            Self((self.0 & !(1 << 3)) | (u32::from(val) << 3))
        }
    }
    impl From<u32> for ErrorIntrEnTWriteVal {
        #[inline(always)]
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ErrorIntrEnTWriteVal> for u32 {
        #[inline(always)]
        fn from(val: ErrorIntrEnTWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ErrorIntrTReadVal(u32);
    impl ErrorIntrTReadVal {
        /// Interrupt Event 0 status bit; Used to indicate SHA3 error.
        #[inline(always)]
        pub fn sha3_error_sts(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
        /// Interrupt Event 1 status bit
        #[inline(always)]
        pub fn error1_sts(&self) -> bool {
            ((self.0 >> 1) & 1) != 0
        }
        /// Interrupt Event 2 status bit
        #[inline(always)]
        pub fn error2_sts(&self) -> bool {
            ((self.0 >> 2) & 1) != 0
        }
        /// Interrupt Event 3 status bit
        #[inline(always)]
        pub fn error3_sts(&self) -> bool {
            ((self.0 >> 3) & 1) != 0
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        #[inline(always)]
        pub fn modify(self) -> ErrorIntrTWriteVal {
            ErrorIntrTWriteVal(self.0)
        }
    }
    impl From<u32> for ErrorIntrTReadVal {
        #[inline(always)]
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ErrorIntrTReadVal> for u32 {
        #[inline(always)]
        fn from(val: ErrorIntrTReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ErrorIntrTWriteVal(u32);
    impl ErrorIntrTWriteVal {
        /// Interrupt Event 0 status bit; Used to indicate SHA3 error.
        #[inline(always)]
        pub fn sha3_error_sts(self, val: bool) -> Self {
            Self((self.0 & !(1 << 0)) | (u32::from(val) << 0))
        }
        /// Interrupt Event 1 status bit
        #[inline(always)]
        pub fn error1_sts(self, val: bool) -> Self {
            Self((self.0 & !(1 << 1)) | (u32::from(val) << 1))
        }
        /// Interrupt Event 2 status bit
        #[inline(always)]
        pub fn error2_sts(self, val: bool) -> Self {
            Self((self.0 & !(1 << 2)) | (u32::from(val) << 2))
        }
        /// Interrupt Event 3 status bit
        #[inline(always)]
        pub fn error3_sts(self, val: bool) -> Self {
            Self((self.0 & !(1 << 3)) | (u32::from(val) << 3))
        }
    }
    impl From<u32> for ErrorIntrTWriteVal {
        #[inline(always)]
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ErrorIntrTWriteVal> for u32 {
        #[inline(always)]
        fn from(val: ErrorIntrTWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ErrorIntrTrigTReadVal(u32);
    impl ErrorIntrTrigTReadVal {
        /// Interrupt Trigger 0 bit
        #[inline(always)]
        pub fn sha3_error_trig(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
        /// Interrupt Trigger 1 bit
        #[inline(always)]
        pub fn error1_trig(&self) -> bool {
            ((self.0 >> 1) & 1) != 0
        }
        /// Interrupt Trigger 2 bit
        #[inline(always)]
        pub fn error2_trig(&self) -> bool {
            ((self.0 >> 2) & 1) != 0
        }
        /// Interrupt Trigger 3 bit
        #[inline(always)]
        pub fn error3_trig(&self) -> bool {
            ((self.0 >> 3) & 1) != 0
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        #[inline(always)]
        pub fn modify(self) -> ErrorIntrTrigTWriteVal {
            ErrorIntrTrigTWriteVal(self.0)
        }
    }
    impl From<u32> for ErrorIntrTrigTReadVal {
        #[inline(always)]
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ErrorIntrTrigTReadVal> for u32 {
        #[inline(always)]
        fn from(val: ErrorIntrTrigTReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct ErrorIntrTrigTWriteVal(u32);
    impl ErrorIntrTrigTWriteVal {
        /// Interrupt Trigger 0 bit
        #[inline(always)]
        pub fn sha3_error_trig(self, val: bool) -> Self {
            Self((self.0 & !(1 << 0)) | (u32::from(val) << 0))
        }
        /// Interrupt Trigger 1 bit
        #[inline(always)]
        pub fn error1_trig(self, val: bool) -> Self {
            Self((self.0 & !(1 << 1)) | (u32::from(val) << 1))
        }
        /// Interrupt Trigger 2 bit
        #[inline(always)]
        pub fn error2_trig(self, val: bool) -> Self {
            Self((self.0 & !(1 << 2)) | (u32::from(val) << 2))
        }
        /// Interrupt Trigger 3 bit
        #[inline(always)]
        pub fn error3_trig(self, val: bool) -> Self {
            Self((self.0 & !(1 << 3)) | (u32::from(val) << 3))
        }
    }
    impl From<u32> for ErrorIntrTrigTWriteVal {
        #[inline(always)]
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<ErrorIntrTrigTWriteVal> for u32 {
        #[inline(always)]
        fn from(val: ErrorIntrTrigTWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct GlobalIntrEnTReadVal(u32);
    impl GlobalIntrEnTReadVal {
        /// Global enable bit for all events of type 'Error'
        #[inline(always)]
        pub fn error_en(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
        /// Global enable bit for all events of type 'Notification'
        #[inline(always)]
        pub fn notif_en(&self) -> bool {
            ((self.0 >> 1) & 1) != 0
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        #[inline(always)]
        pub fn modify(self) -> GlobalIntrEnTWriteVal {
            GlobalIntrEnTWriteVal(self.0)
        }
    }
    impl From<u32> for GlobalIntrEnTReadVal {
        #[inline(always)]
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<GlobalIntrEnTReadVal> for u32 {
        #[inline(always)]
        fn from(val: GlobalIntrEnTReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct GlobalIntrEnTWriteVal(u32);
    impl GlobalIntrEnTWriteVal {
        /// Global enable bit for all events of type 'Error'
        #[inline(always)]
        pub fn error_en(self, val: bool) -> Self {
            Self((self.0 & !(1 << 0)) | (u32::from(val) << 0))
        }
        /// Global enable bit for all events of type 'Notification'
        #[inline(always)]
        pub fn notif_en(self, val: bool) -> Self {
            Self((self.0 & !(1 << 1)) | (u32::from(val) << 1))
        }
    }
    impl From<u32> for GlobalIntrEnTWriteVal {
        #[inline(always)]
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<GlobalIntrEnTWriteVal> for u32 {
        #[inline(always)]
        fn from(val: GlobalIntrEnTWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct GlobalIntrTReadVal(u32);
    impl GlobalIntrTReadVal {
        /// Interrupt Event Aggregation status bit
        #[inline(always)]
        pub fn agg_sts(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
    }
    impl From<u32> for GlobalIntrTReadVal {
        #[inline(always)]
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<GlobalIntrTReadVal> for u32 {
        #[inline(always)]
        fn from(val: GlobalIntrTReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct IntrCountIncrTReadVal(u32);
    impl IntrCountIncrTReadVal {
        /// Pulse mirrors interrupt event occurrence
        #[inline(always)]
        pub fn pulse(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
    }
    impl From<u32> for IntrCountIncrTReadVal {
        #[inline(always)]
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<IntrCountIncrTReadVal> for u32 {
        #[inline(always)]
        fn from(val: IntrCountIncrTReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct NotifIntrEnTReadVal(u32);
    impl NotifIntrEnTReadVal {
        /// Enable bit for Command Done Interrupt.
        /// Interrupt is asserted when there is valid digest to be read.
        #[inline(always)]
        pub fn notif_cmd_done_en(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
        /// Enable bit for MSG FIFO Empty Interrupt.
        /// Interrupt is asserted when MSG FIFO Is Empty.
        #[inline(always)]
        pub fn notif_msg_fifo_empty_en(&self) -> bool {
            ((self.0 >> 1) & 1) != 0
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        #[inline(always)]
        pub fn modify(self) -> NotifIntrEnTWriteVal {
            NotifIntrEnTWriteVal(self.0)
        }
    }
    impl From<u32> for NotifIntrEnTReadVal {
        #[inline(always)]
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<NotifIntrEnTReadVal> for u32 {
        #[inline(always)]
        fn from(val: NotifIntrEnTReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct NotifIntrEnTWriteVal(u32);
    impl NotifIntrEnTWriteVal {
        /// Enable bit for Command Done Interrupt.
        /// Interrupt is asserted when there is valid digest to be read.
        #[inline(always)]
        pub fn notif_cmd_done_en(self, val: bool) -> Self {
            Self((self.0 & !(1 << 0)) | (u32::from(val) << 0))
        }
        /// Enable bit for MSG FIFO Empty Interrupt.
        /// Interrupt is asserted when MSG FIFO Is Empty.
        #[inline(always)]
        pub fn notif_msg_fifo_empty_en(self, val: bool) -> Self {
            Self((self.0 & !(1 << 1)) | (u32::from(val) << 1))
        }
    }
    impl From<u32> for NotifIntrEnTWriteVal {
        #[inline(always)]
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<NotifIntrEnTWriteVal> for u32 {
        #[inline(always)]
        fn from(val: NotifIntrEnTWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct NotifIntrTReadVal(u32);
    impl NotifIntrTReadVal {
        /// SHA3 cmd_done indicate
        /// 1. SHA3 absorbing has been completed, 1st rate of digest is ready.
        #[inline(always)]
        pub fn notif_cmd_done_sts(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
        /// MSG_FIFO Empty Interrupt status bit.
        /// This interrupt is raised only if the message FIFO is actually writable by software, i.e., if all of the following conditions are met:
        /// i) The SHA3 block is in the Absorb state.
        /// ii) Software has not yet written the Process command to finish the absorption process.
        /// For the interrupt to be raised, the message FIFO must also have been full previously.
        /// Otherwise, the hardware empties the FIFO faster than software can fill it
        /// and there is no point in interrupting the software to inform it about the message FIFO being empty.
        #[inline(always)]
        pub fn notif_msg_fifo_empty_sts(&self) -> bool {
            ((self.0 >> 1) & 1) != 0
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        #[inline(always)]
        pub fn modify(self) -> NotifIntrTWriteVal {
            NotifIntrTWriteVal(self.0)
        }
    }
    impl From<u32> for NotifIntrTReadVal {
        #[inline(always)]
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<NotifIntrTReadVal> for u32 {
        #[inline(always)]
        fn from(val: NotifIntrTReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct NotifIntrTWriteVal(u32);
    impl NotifIntrTWriteVal {
        /// SHA3 cmd_done indicate
        /// 1. SHA3 absorbing has been completed, 1st rate of digest is ready.
        #[inline(always)]
        pub fn notif_cmd_done_sts(self, val: bool) -> Self {
            Self((self.0 & !(1 << 0)) | (u32::from(val) << 0))
        }
    }
    impl From<u32> for NotifIntrTWriteVal {
        #[inline(always)]
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<NotifIntrTWriteVal> for u32 {
        #[inline(always)]
        fn from(val: NotifIntrTWriteVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct NotifIntrTrigTReadVal(u32);
    impl NotifIntrTrigTReadVal {
        /// Interrupt Trigger 0 bit
        #[inline(always)]
        pub fn notif_cmd_done_trig(&self) -> bool {
            ((self.0 >> 0) & 1) != 0
        }
        /// MSG_FIFO Empty Interrupt Trigger 0 bit
        #[inline(always)]
        pub fn notif_msg_fifo_empty_trig(&self) -> bool {
            ((self.0 >> 1) & 1) != 0
        }
        /// Construct a WriteVal that can be used to modify the contents of this register value.
        #[inline(always)]
        pub fn modify(self) -> NotifIntrTrigTWriteVal {
            NotifIntrTrigTWriteVal(self.0)
        }
    }
    impl From<u32> for NotifIntrTrigTReadVal {
        #[inline(always)]
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<NotifIntrTrigTReadVal> for u32 {
        #[inline(always)]
        fn from(val: NotifIntrTrigTReadVal) -> u32 {
            val.0
        }
    }
    #[derive(Clone, Copy)]
    pub struct NotifIntrTrigTWriteVal(u32);
    impl NotifIntrTrigTWriteVal {
        /// Interrupt Trigger 0 bit
        #[inline(always)]
        pub fn notif_cmd_done_trig(self, val: bool) -> Self {
            Self((self.0 & !(1 << 0)) | (u32::from(val) << 0))
        }
        /// MSG_FIFO Empty Interrupt Trigger 0 bit
        #[inline(always)]
        pub fn notif_msg_fifo_empty_trig(self, val: bool) -> Self {
            Self((self.0 & !(1 << 1)) | (u32::from(val) << 1))
        }
    }
    impl From<u32> for NotifIntrTrigTWriteVal {
        #[inline(always)]
        fn from(val: u32) -> Self {
            Self(val)
        }
    }
    impl From<NotifIntrTrigTWriteVal> for u32 {
        #[inline(always)]
        fn from(val: NotifIntrTrigTWriteVal) -> u32 {
            val.0
        }
    }
}
pub mod enums {
    //! Enumerations used by some register fields.
    pub mod selector {}
}
pub mod meta {
    //! Additional metadata needed by ureg.
    pub type Name = ureg::ReadOnlyReg32<u32>;
    pub type Version = ureg::ReadOnlyReg32<u32>;
    pub type AlertTest = ureg::WriteOnlyReg32<0, crate::sha3::regs::AlertTestWriteVal>;
    pub type CfgRegwen = ureg::ReadOnlyReg32<crate::sha3::regs::CfgRegwenReadVal>;
    pub type CfgShadowed = ureg::ReadWriteReg32<
        0,
        crate::sha3::regs::CfgShadowedReadVal,
        crate::sha3::regs::CfgShadowedWriteVal,
    >;
    pub type Cmd =
        ureg::ReadWriteReg32<0, crate::sha3::regs::CmdReadVal, crate::sha3::regs::CmdWriteVal>;
    pub type Status = ureg::ReadOnlyReg32<crate::sha3::regs::StatusReadVal>;
    pub type ErrCode = ureg::ReadOnlyReg32<u32>;
    pub type State = ureg::ReadOnlyReg32<u32>;
    pub type MsgFifo = ureg::WriteOnlyReg32<0, u32>;
    pub type IntrBlockRfGlobalIntrEnR = ureg::ReadWriteReg32<
        0,
        crate::sha512_acc::regs::GlobalIntrEnTReadVal,
        crate::sha512_acc::regs::GlobalIntrEnTWriteVal,
    >;
    pub type IntrBlockRfErrorIntrEnR = ureg::ReadWriteReg32<
        0,
        crate::sha3::regs::ErrorIntrEnTReadVal,
        crate::sha3::regs::ErrorIntrEnTWriteVal,
    >;
    pub type IntrBlockRfNotifIntrEnR = ureg::ReadWriteReg32<
        0,
        crate::sha3::regs::NotifIntrEnTReadVal,
        crate::sha3::regs::NotifIntrEnTWriteVal,
    >;
    pub type IntrBlockRfErrorGlobalIntrR =
        ureg::ReadOnlyReg32<crate::sha512_acc::regs::GlobalIntrTReadVal>;
    pub type IntrBlockRfNotifGlobalIntrR =
        ureg::ReadOnlyReg32<crate::sha512_acc::regs::GlobalIntrTReadVal>;
    pub type IntrBlockRfErrorInternalIntrR = ureg::ReadWriteReg32<
        0,
        crate::sha3::regs::ErrorIntrTReadVal,
        crate::sha3::regs::ErrorIntrTWriteVal,
    >;
    pub type IntrBlockRfNotifInternalIntrR = ureg::ReadWriteReg32<
        0,
        crate::sha3::regs::NotifIntrTReadVal,
        crate::sha3::regs::NotifIntrTWriteVal,
    >;
    pub type IntrBlockRfErrorIntrTrigR = ureg::ReadWriteReg32<
        0,
        crate::sha3::regs::ErrorIntrTrigTReadVal,
        crate::sha3::regs::ErrorIntrTrigTWriteVal,
    >;
    pub type IntrBlockRfNotifIntrTrigR = ureg::ReadWriteReg32<
        0,
        crate::sha3::regs::NotifIntrTrigTReadVal,
        crate::sha3::regs::NotifIntrTrigTWriteVal,
    >;
    pub type IntrBlockRfSha3ErrorIntrCountR = ureg::ReadWriteReg32<0, u32, u32>;
    pub type IntrBlockRfError1IntrCountR = ureg::ReadWriteReg32<0, u32, u32>;
    pub type IntrBlockRfError2IntrCountR = ureg::ReadWriteReg32<0, u32, u32>;
    pub type IntrBlockRfError3IntrCountR = ureg::ReadWriteReg32<0, u32, u32>;
    pub type IntrBlockRfNotifCmdDoneIntrCountR = ureg::ReadWriteReg32<0, u32, u32>;
    pub type IntrBlockRfSha3ErrorIntrCountIncrR =
        ureg::ReadOnlyReg32<crate::sha512_acc::regs::IntrCountIncrTReadVal>;
    pub type IntrBlockRfError1IntrCountIncrR =
        ureg::ReadOnlyReg32<crate::sha512_acc::regs::IntrCountIncrTReadVal>;
    pub type IntrBlockRfError2IntrCountIncrR =
        ureg::ReadOnlyReg32<crate::sha512_acc::regs::IntrCountIncrTReadVal>;
    pub type IntrBlockRfError3IntrCountIncrR =
        ureg::ReadOnlyReg32<crate::sha512_acc::regs::IntrCountIncrTReadVal>;
    pub type IntrBlockRfNotifCmdDoneIntrCountIncrR =
        ureg::ReadOnlyReg32<crate::sha512_acc::regs::IntrCountIncrTReadVal>;
}
