# Licensed under the Apache-2.0 license

[package]
name = "caliptra-drivers-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { version = "0.4", optional = true }
afl = { version = "0.15", optional = true }
zerocopy = "0.6"
arbitrary = { version = "1.3", optional = true, features = ["derive"] }
sha2 = { version = "0.10", default-features = false, features = ["compress"] }

[patch.crates-io]
byteorder = { git = "https://github.com/benjamindoron/byteorder.git", branch = "struct_aware" }
zerocopy = { git = "https://github.com/benjamindoron/zerocopy.git", branch = "struct_aware" }

[dependencies.caliptra-drivers]
path = ".."

[dependencies.caliptra-image-types]
path = "../../image/types"
features = ["arbitrary"]

[dependencies.caliptra-lms-types]
path = "../../lms-types"
features = ["arbitrary"]

[features]
struct-aware = ["arbitrary"]

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[profile.release]
debug = 1

[[bin]]
name = "fuzz_target_lms"
path = "src/fuzz_target_lms.rs"
test = false
doc = false
