# Licensed under the Apache-2.0 license

[package]
name = "caliptra-fmc-mock-rt"
version = "0.1.0"
edition = "2021"

[dependencies]
caliptra-cpu.workspace = true
caliptra-drivers.workspace = true
caliptra-registers.workspace = true
caliptra_common = { workspace = true, default-features = false }
ufmt.workspace = true
zerocopy.workspace = true

[build-dependencies]
cfg-if.workspace = true

[dev-dependencies]
caliptra-builder.workspace = true

[features]
riscv = ["caliptra-cpu/riscv"]
default = ["std"]
emu = ["caliptra_common/emu", "caliptra-drivers/emu"]
std = ["ufmt/std", "caliptra_common/std"]
