# Licensed under the Apache-2.0 license

[package]
name = "caliptra-fmc-mock-rt"
version = "0.1.0"
edition = "2021"

[dependencies]
caliptra_common = { workspace = true, default-features = false }
caliptra-cpu.workspace = true
caliptra-drivers = { workspace = true, features = ["no-cfi"] }
caliptra-registers.workspace = true
ufmt.workspace = true
zerocopy.workspace = true
ureg.workspace = true

[build-dependencies]
cfg-if.workspace = true
caliptra_common = { workspace = true, default-features = false }
caliptra-gen-linker-scripts.workspace = true

[dev-dependencies]
caliptra-builder.workspace = true

[features]
default = ["std"]
emu = ["caliptra_common/emu", "caliptra-drivers/emu"]
riscv = ["caliptra-cpu/riscv"]
std = ["ufmt/std", "caliptra_common/std"]
interactive_test = []
