# Licensed under the Apache-2.0 license

[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]

[profile.release]
panic = "abort"
opt-level = "z" # Optimize for size.
lto = true

[profile.dev]
panic = "abort"
lto = true
