# Licensed under the Apache-2.0 license

[package]
name = "caliptra-x509-rustcrypto-mldsa"
version = "0.1.0"
edition = "2021"

[dependencies]
ml-dsa = "0.0.4"
x509-cert = { version = "0.2.5", features = ["builder", "hazmat"] }
rand = "0.8"
der = { version = "0.7.10", features = ["derive", "alloc"] }
spki = {  version = "0.7.3", features = ["alloc"] }
sha2 = { version = "0.10.8", default-features = false, features = ["compress"] }
signature = "2.2.0"
const-oid = "0.9.6"
hex = "0.4.3"
convert_case = "0.6.0"
quote = "1.0"
sha1 = "0.10.6"
