name: Publish Docker Build Image

on:
  push:
    branches:
      - main
    paths:
      - 'ci-tools/build-image/Dockerfile'
  workflow_dispatch:

jobs:
  # Publishes "ghcr.io/chipsalliance/caliptra-build-image".
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ci-tools/build-image
          file: ci-tools/build-image/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/caliptra-build-image:latest
            ghcr.io/${{ github.repository_owner }}/caliptra-build-image:${{ github.sha }}
